services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5  

  catalog-api:
    build:
      context: .
      dockerfile: src/Catalog.Api/Dockerfile
    container_name: ecommerce_catalog_api
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Postgres: ${CATALOG_POSTGRES_CONNECTION_STRING}
      RabbitMq__HostName: ${RABBITMQ_HOST}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy 
  
  order-api:
    build:
      context: .
      dockerfile: src/Order.Api/Dockerfile
    container_name: ecommerce_order_api
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Postgres: ${ORDER_POSTGRES_CONNECTION_STRING}
      RabbitMq__HostName: ${RABBITMQ_HOST}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
    ports:
      - "5002:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  payment-api:
    build:
      context: .
      dockerfile: src/Payment.Api/Dockerfile
    container_name: ecommerce_payment_api
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      RabbitMq__HostName: ${RABBITMQ_HOST}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
    ports:
      - "5003:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-api:
    build:
      context: .
      dockerfile: src/Notification.Api/Dockerfile
    container_name: ecommerce_notification_api
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      RabbitMq__HostName: ${RABBITMQ_HOST}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
    ports:
      - "5004:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
volumes:
  postgres_data: